USE master;
GO

CREATE DATABASE TPIcomercioBD
COLLATE Latin1_General_CS_AS;

USE TPIcomercioBD;
GO


-- ROL (Admin, Vendedor)
CREATE TABLE ROL (
    ID TINYINT IDENTITY(1,1) PRIMARY KEY,
    ROL VARCHAR(100) NOT NULL -- 1 ADMIN - 2 EMPLEADO - 3 CLIENTE
);
GO

-- MARCA
CREATE TABLE MARCA (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR(250) NULL,
    ACTIVO BIT DEFAULT 1
);
GO

-- CATEGORIA
CREATE TABLE CATEGORIA (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR(250) NULL,
    ACTIVO BIT DEFAULT 1
);
GO

-- TIPO_PAGO
CREATE TABLE TIPO_PAGO (
    ID TINYINT IDENTITY(1,1) PRIMARY KEY, 
    NOMBRE VARCHAR(100) NOT NULL UNIQUE, -- EFECTIVO , TRANSFERENCIA , TARJETA DE CREDITO, CHEQUE
    DESCRIPCION VARCHAR(250) NULL
);
GO

-- =============================================
-- 2. PRODUCTO
-- =============================================

CREATE TABLE PRODUCTO (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    PRECIO DECIMAL(10,2) CHECK (PRECIO > 0),
    DESCRIPCION_CORTA VARCHAR(250) NOT NULL,
	DESCRIPCION_EXTENDIDA VARCHAR(MAX) NOT NULL,
    STOCK INT NOT NULL DEFAULT 0 CHECK (STOCK >= 0),
    STOCK_MINIMO INT NOT NULL DEFAULT 0 CHECK (STOCK_MINIMO >= 0),
    ID_MARCA BIGINT NOT NULL,
    ID_CATEGORIA BIGINT NOT NULL,
    ACTIVO BIT DEFAULT 1,
    CONSTRAINT FK_PRODUCTO_MARCA FOREIGN KEY (ID_MARCA) REFERENCES MARCA(ID),
    CONSTRAINT FK_PRODUCTO_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID)
);
GO

-- =============================================
-- 3. USUARIO 
-- =============================================

CREATE TABLE USUARIO (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    NICKNAME VARCHAR(100) NOT NULL UNIQUE,
    CONTRASENA VARCHAR(250) NOT NULL,
    EMAIL VARCHAR(250) NULL,
    ROLE_ID TINYINT NOT NULL,
    ACTIVO BIT DEFAULT 1,
    CONSTRAINT FK_USUARIO_ROL FOREIGN KEY (ROLE_ID) REFERENCES ROL(ID)
);
GO

-- =============================================
-- 4. CLIENTE
-- =============================================

CREATE TABLE CLIENTE (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(100) NULL,
    FECHA_REGISTRO DATE NOT NULL DEFAULT GETDATE(),
    ROLE_ID TINYINT NULL,
	ID_USUARIO BIGINT NULL UNIQUE,
    RAZON_SOCIAL VARCHAR(250) NULL,
	ACTIVO BIT DEFAULT 1,
    CONSTRAINT FK_CLIENTE_ROL FOREIGN KEY (ROLE_ID) REFERENCES ROL(ID),
	CONSTRAINT FK_CLIENTE_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
	CONSTRAINT CK_CLIENTE_ROL CHECK (ROLE_ID = 3 OR ROLE_ID IS NULL)
);
GO

-- =============================================
-- 5. EMPLEADO
-- =============================================

CREATE TABLE EMPLEADO (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(100) NULL,
    FECHAINGRESO DATE NOT NULL DEFAULT GETDATE(),
    SUELDO MONEY NOT NULL DEFAULT 0 CHECK (SUELDO >= 0),
    ID_USUARIO BIGINT NOT NULL UNIQUE,
	ACTIVO BIT DEFAULT 1,
    CONSTRAINT FK_EMPLEADO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)
);
GO

-- =============================================
-- 9. VENTA
-- =============================================

CREATE TABLE VENTA (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    FECHAVENTA DATE NOT NULL DEFAULT GETDATE(),
    MONTOTOTAL MONEY NOT NULL CHECK (MONTOTOTAL > 0),
    ID_TIPO_PAGO TINYINT NOT NULL,
    ID_CLIENTE BIGINT NOT NULL,
    NUM_FACTURA VARCHAR(30) NULL UNIQUE, -- Se genera en app o trigger
    CONSTRAINT FK_VENTA_TIPO_PAGO FOREIGN KEY (ID_TIPO_PAGO) REFERENCES TIPO_PAGO(ID),
    CONSTRAINT FK_VENTA_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID),
);
GO

-- =============================================
-- 10. DETALLE_VENTA
-- =============================================

CREATE TABLE DETALLE_VENTA (
	ID_VENTA BIGINT NOT NULL,
    ID_PRODUCTO BIGINT NOT NULL,
    CANTIDAD SMALLINT NOT NULL CHECK (CANTIDAD > 0),
    PRECIO_UNITARIO MONEY NOT NULL CHECK (PRECIO_UNITARIO > 0),
    PRIMARY KEY (ID_VENTA, ID_PRODUCTO),  -- PK compuesta
    CONSTRAINT FK_DETALLE_VENTA_VENTA FOREIGN KEY (ID_VENTA) REFERENCES VENTA(ID) ON DELETE CASCADE,
    CONSTRAINT FK_DETALLE_VENTA_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID)
);
GO


-- ===================================================================
-- ================	FUNCIONES DE SISTEMA	=========================
-- ===================================================================

--CREACION DE VISTA PARA LISTAR PRODUCTOS ACTIVOS
CREATE VIEW vw_ProductosActivos AS
SELECT
    prod.ID,
    prod.NOMBRE,
    prod.PRECIO,
	prod.DESCRIPCION_CORTA,
    prod.DESCRIPCION_EXTENDIDA,
    prod.STOCK,
    prod.STOCK_MINIMO,
    marc.ID AS IdMarca,
    marc.NOMBRE AS NombreMarca,
    marc.DESCRIPCION AS DescripcionMarca,
    cat.ID AS IdCategoria,
    cat.NOMBRE AS NombreCategoria,
    cat.DESCRIPCION AS DescripcionCategoria,
    prod.ACTIVO
	FROM PRODUCTO prod
	INNER JOIN MARCA marc ON marc.ID = prod.ID_MARCA
	INNER JOIN CATEGORIA cat ON cat.ID = prod.ID_CATEGORIA
	WHERE prod.ACTIVO = 1;

	----------------------------------------------------------

-- PROCEDIMIENTO ALMACENADO PARA LA CREACION DE USUARIOS
CREATE PROCEDURE sp_AgregarUsuario
    @Nickname NVARCHAR(50),
    @Contrasena NVARCHAR(255),
    @Email NVARCHAR(100),
    @RolId INT,
    @Activo BIT = 1
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRY
        BEGIN TRANSACTION;

        IF EXISTS (SELECT 1 FROM USUARIO WHERE NICKNAME = @Nickname)
            THROW 50001, 'El nickname ya existe', 1;
        
        IF EXISTS (SELECT 1 FROM USUARIO WHERE EMAIL = @Email)
            THROW 50002, 'El email ya está registrado', 1;
        
        IF @RolId NOT IN (2, 3)
            THROW 50003, 'Rol no permitido', 1;

        INSERT INTO USUARIO (NICKNAME, CONTRASENA, EMAIL, ROLE_ID, ACTIVO)
        VALUES (@Nickname, @Contrasena, @Email, @RolId, @Activo);

        COMMIT TRANSACTION;
        SELECT SCOPE_IDENTITY() AS NuevoId;
    END TRY
    BEGIN CATCH
        ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END

	----------------------------------------------------------