USE master;
GO

CREATE DATABASE TPIcomercioBD
COLLATE Latin1_General_CS_AS;

USE TPIcomercioBD;
GO


-- ROL (Admin, Vendedor)
CREATE TABLE ROL (
    ID TINYINT IDENTITY(1,1) PRIMARY KEY,
    ROL VARCHAR(100) NOT NULL
);
GO

-- MARCA
CREATE TABLE MARCA (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR(250) NULL,
    ACTIVO BIT DEFAULT 1
);
GO

-- CATEGORIA
CREATE TABLE CATEGORIA (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR(250) NULL,
    ACTIVO BIT DEFAULT 1
);
GO

-- TIPO_PAGO
CREATE TABLE TIPO_PAGO (
    ID TINYINT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR(250) NULL
);
GO

-- PROVEEDOR
CREATE TABLE PROVEEDOR (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(250) NOT NULL,
    TELEFONO VARCHAR(100) NULL
);
GO

-- =============================================
-- 2. PRODUCTO
-- =============================================

CREATE TABLE PRODUCTO (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    PRECIO DECIMAL(10,2) CHECK (PRECIO > 0),
    DESCRIPCION VARCHAR(250) NULL,
    STOCK INT NOT NULL DEFAULT 0 CHECK (STOCK >= 0),
    STOCK_MINIMO INT NOT NULL DEFAULT 0 CHECK (STOCK_MINIMO >= 0),
    PORCENTAJE_GANANCIA DECIMAL(5,2) NOT NULL DEFAULT 30.00 CHECK (PORCENTAJE_GANANCIA >= 0),
    ID_MARCA BIGINT NOT NULL,
    ID_CATEGORIA BIGINT NOT NULL,
    ACTIVO BIT DEFAULT 1,
    CONSTRAINT FK_PRODUCTO_MARCA FOREIGN KEY (ID_MARCA) REFERENCES MARCA(ID),
    CONSTRAINT FK_PRODUCTO_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID)
);
GO

-- =============================================
-- 3. USUARIO 
-- =============================================

CREATE TABLE USUARIO (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    NICKNAME VARCHAR(100) NOT NULL UNIQUE,
    CONTRASENA VARCHAR(250) NOT NULL,
    EMAIL VARCHAR(250) NULL,
    ROLE_ID TINYINT NOT NULL,
    ACTIVO BIT DEFAULT 1,
    CONSTRAINT FK_USUARIO_ROL FOREIGN KEY (ROLE_ID) REFERENCES ROL(ID)
);
GO

-- =============================================
-- 4. CLIENTE
-- =============================================

CREATE TABLE CLIENTE (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(100) NULL,
    FECHA_REGISTRO DATE NOT NULL DEFAULT GETDATE(),
    ROLE_ID TINYINT NULL,
	ID_USUARIO BIGINT NULL UNIQUE,
    RAZON_SOCIAL VARCHAR(250) NULL,
    CONSTRAINT FK_CLIENTE_ROL FOREIGN KEY (ROLE_ID) REFERENCES ROL(ID),
	CONSTRAINT FK_CLIENTE_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
	CONSTRAINT CK_CLIENTE_ROL CHECK (ROLE_ID = 3 OR ROLE_ID IS NULL)
);
GO

-- =============================================
-- 5. EMPLEADO
-- =============================================

CREATE TABLE EMPLEADO (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(100) NULL,
    FECHAINGRESO DATE NOT NULL DEFAULT GETDATE(),
    SUELDO MONEY NOT NULL DEFAULT 0 CHECK (SUELDO >= 0),
    ID_USUARIO BIGINT NOT NULL UNIQUE,
    CONSTRAINT FK_EMPLEADO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)
);
GO

-- =============================================
-- 6. PRODUCTO_PROVEEDOR
-- =============================================

CREATE TABLE PRODUCTO_PROVEEDOR (
    ID_PRODUCTO BIGINT NOT NULL,
    ID_PROVEEDOR BIGINT NOT NULL,
    PRIMARY KEY (ID_PRODUCTO, ID_PROVEEDOR),
    CONSTRAINT FK_PP_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID) ON DELETE CASCADE,
    CONSTRAINT FK_PP_PROVEEDOR FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR(ID) ON DELETE CASCADE
);
GO

-- =============================================
-- 7. COMPRA
-- =============================================

CREATE TABLE COMPRA (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    FECHACOMPRA DATE NOT NULL DEFAULT GETDATE(),
    MONTOTOTAL MONEY NOT NULL CHECK (MONTOTOTAL > 0),
    ID_TIPO_PAGO TINYINT NOT NULL,
    ID_PROVEEDOR BIGINT NOT NULL,
    CONSTRAINT FK_COMPRA_TIPO_PAGO FOREIGN KEY (ID_TIPO_PAGO) REFERENCES TIPO_PAGO(ID),
    CONSTRAINT FK_COMPRA_PROVEEDOR FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR(ID)
);
GO

-- =============================================
-- 8. DETALLE_COMPRA
-- =============================================

CREATE TABLE DETALLE_COMPRA (
	ID_COMPRA BIGINT NOT NULL,
    ID_PRODUCTO BIGINT NOT NULL,
    CANTIDAD SMALLINT NOT NULL CHECK (CANTIDAD > 0),
    PRECIO_UNITARIO MONEY NOT NULL CHECK (PRECIO_UNITARIO > 0),
    PRIMARY KEY (ID_COMPRA, ID_PRODUCTO),  -- PK compuesta
    CONSTRAINT FK_DETALLE_COMPRA_COMPRA FOREIGN KEY (ID_COMPRA) REFERENCES COMPRA(ID) ON DELETE CASCADE,
    CONSTRAINT FK_DETALLE_COMPRA_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID)
);
GO

-- =============================================
-- 9. VENTA
-- =============================================

CREATE TABLE VENTA (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    FECHAVENTA DATE NOT NULL DEFAULT GETDATE(),
    MONTOTOTAL MONEY NOT NULL CHECK (MONTOTOTAL > 0),
    ID_TIPO_PAGO TINYINT NOT NULL,
    ID_CLIENTE BIGINT NOT NULL,
    NUM_FACTURA VARCHAR(30) NULL UNIQUE, -- Se genera en app o trigger
	ID_EMPLEADO BIGINT NULL,
    CONSTRAINT FK_VENTA_TIPO_PAGO FOREIGN KEY (ID_TIPO_PAGO) REFERENCES TIPO_PAGO(ID),
    CONSTRAINT FK_VENTA_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID),
	CONSTRAINT FK_VENTA_EMPLEADO FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID),
);
GO

-- =============================================
-- 10. DETALLE_VENTA
-- =============================================

CREATE TABLE DETALLE_VENTA (
	ID_VENTA BIGINT NOT NULL,
    ID_PRODUCTO BIGINT NOT NULL,
    CANTIDAD SMALLINT NOT NULL CHECK (CANTIDAD > 0),
    PRECIO_UNITARIO MONEY NOT NULL CHECK (PRECIO_UNITARIO > 0),
    PRIMARY KEY (ID_VENTA, ID_PRODUCTO),  -- PK compuesta
    CONSTRAINT FK_DETALLE_VENTA_VENTA FOREIGN KEY (ID_VENTA) REFERENCES VENTA(ID) ON DELETE CASCADE,
    CONSTRAINT FK_DETALLE_VENTA_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID)
);
GO
