USE master;
GO

-- =============================================
-- CREAR BASE DE DATOS (Case-Sensitive)
-- =============================================
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'TPIcomercioBD')
BEGIN
    CREATE DATABASE TPIcomercioBD
    COLLATE Latin1_General_CS_AS;
    PRINT 'Base de datos creada: TPIcomercioBD (Case-Sensitive)';
END
GO

USE TPIcomercioBD;
GO

-- =============================================
-- 1. ROL (Admin, Vendedor, Cliente)
-- =============================================
CREATE TABLE ROL (
    ID TINYINT IDENTITY(1,1) PRIMARY KEY,
    ROL VARCHAR(100) NOT NULL
);
GO

INSERT INTO ROL (ROL) VALUES ('Admin'), ('Vendedor'), ('Cliente');
GO

-- =============================================
-- 2. MARCA
-- =============================================
CREATE TABLE MARCA (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR(250) NULL
);
GO

-- =============================================
-- 3. CATEGORIA
-- =============================================
CREATE TABLE CATEGORIA (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR(250) NULL
);
GO

-- =============================================
-- 4. TIPO_PAGO
-- =============================================
CREATE TABLE TIPO_PAGO (
    ID TINYINT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR(250) NULL
);
GO

INSERT INTO TIPO_PAGO (NOMBRE) VALUES ('Efectivo'), ('Tarjeta'), ('Transferencia');
GO

-- =============================================
-- 5. PRODUCTO (SIN PROVEEDORES)
-- =============================================
CREATE TABLE PRODUCTO (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    PRECIO DECIMAL(10,2) NOT NULL CHECK (PRECIO > 0),
    DESCRIPCION VARCHAR(250) NULL,
    STOCK INT NOT NULL DEFAULT 0 CHECK (STOCK >= 0),
    STOCK_MINIMO INT NOT NULL DEFAULT 0 CHECK (STOCK_MINIMO >= 0),
    ID_MARCA BIGINT NOT NULL,
    ID_CATEGORIA BIGINT NOT NULL,
    CONSTRAINT FK_PRODUCTO_MARCA FOREIGN KEY (ID_MARCA) REFERENCES MARCA(ID),
    CONSTRAINT FK_PRODUCTO_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID)
);
GO

-- =============================================
-- 6. USUARIO (solo empleados y admin)
-- =============================================
CREATE TABLE USUARIO (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    NICKNAME VARCHAR(100) NOT NULL UNIQUE COLLATE Latin1_General_CS_AS,
    CONTRASENA VARCHAR(250) NOT NULL,
    EMAIL VARCHAR(250) NULL COLLATE Latin1_General_CS_AS,
    ROLE_ID TINYINT NOT NULL,
    CONSTRAINT FK_USUARIO_ROL FOREIGN KEY (ROLE_ID) REFERENCES ROL(ID),
    CONSTRAINT CK_USUARIO_ROL_EMPLEADO CHECK (ROLE_ID IN (1, 2)) -- Solo Admin/Vendedor
);
GO

-- =============================================
-- 7. CLIENTE (con cuenta opcional)
-- =============================================
CREATE TABLE CLIENTE (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(100) NULL,
    FECHA_REGISTRO DATE NOT NULL DEFAULT GETDATE(),
    RAZON_SOCIAL VARCHAR(250) NULL,
    ID_USUARIO BIGINT NULL UNIQUE,
    ROLE_ID TINYINT NULL,
    CONSTRAINT FK_CLIENTE_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
    CONSTRAINT FK_CLIENTE_ROL FOREIGN KEY (ROLE_ID) REFERENCES ROL(ID),
    CONSTRAINT CK_CLIENTE_ROL CHECK (ROLE_ID = 3 OR ROLE_ID IS NULL)
);
GO

-- =============================================
-- 8. EMPLEADO
-- =============================================
CREATE TABLE EMPLEADO (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(100) NULL,
    FECHAINGRESO DATE NOT NULL DEFAULT GETDATE(),
    SUELDO MONEY NOT NULL DEFAULT 0 CHECK (SUELDO >= 0),
    ID_USUARIO BIGINT NOT NULL UNIQUE,
);
GO

-- =============================================
-- 9. VENTA (con empleado opcional - web/local)
-- =============================================
CREATE TABLE VENTA (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    FECHAVENTA DATE NOT NULL DEFAULT GETDATE(),
    MONTOTOTAL MONEY NOT NULL CHECK (MONTOTOTAL > 0),
    ID_TIPO_PAGO TINYINT NOT NULL,
    ID_CLIENTE BIGINT NOT NULL,
    NUM_FACTURA VARCHAR(30) NULL UNIQUE,
    CONSTRAINT FK_VENTA_TIPO_PAGO FOREIGN KEY (ID_TIPO_PAGO) REFERENCES TIPO_PAGO(ID),
    CONSTRAINT FK_VENTA_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID),
);
GO

-- =============================================
-- 10. DETALLE_VENTA (PK compuesta)
-- =============================================
CREATE TABLE DETALLE_VENTA (
    ID_VENTA BIGINT NOT NULL,
    ID_PRODUCTO BIGINT NOT NULL,
    CANTIDAD SMALLINT NOT NULL CHECK (CANTIDAD > 0),
    PRECIO_UNITARIO MONEY NOT NULL CHECK (PRECIO_UNITARIO > 0),
    PRIMARY KEY (ID_VENTA, ID_PRODUCTO),
    CONSTRAINT FK_DETALLE_VENTA_VENTA 
        FOREIGN KEY (ID_VENTA) REFERENCES VENTA(ID) ON DELETE CASCADE,
    CONSTRAINT FK_DETALLE_VENTA_PRODUCTO 
        FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID)
);
GO