//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace Dominio
{


    public partial class gestionClientes
    {

        /// <summary>
        /// Control gvClientes (o el nombre que uses en tu GridView)
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvClientes;

        /// <summary>
        /// Control ddlPageSize
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlPageSize;

        /// <summary>
        /// Control txtBuscar
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBuscar;

        /// <summary>
        /// Control btnBuscar
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnBuscar;

        /// <summary>
        /// Control lblInfo
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblInfo;
    }
}